---
- name: install scl
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - centos-release-scl

- name: install needed packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - httpd24-httpd
    - httpd24-apr
    - httpd24-apr-util
    - httpd24-httpd-tools
    - httpd24-libnghttp2
    - httpd24-mod_proxy_html
    - httpd24-mod_session
    - httpd24-mod_ssl
    - httpd24-runtime
    - rh-php70
    - rh-php70-php
    - rh-php70-php-bcmath
    - rh-php70-php-cli
    - rh-php70-php-common
    - rh-php70-php-dba
    - rh-php70-php-dbg
    - rh-php70-php-devel
    - rh-php70-php-embedded
    - rh-php70-php-enchant
    - rh-php70-php-fpm
    - rh-php70-php-gd
    - rh-php70-php-gmp
    - rh-php70-php-imap
    - rh-php70-php-intl
    - rh-php70-php-json
    - rh-php70-php-ldap
    - rh-php70-php-mbstring
    - rh-php70-php-mysqlnd
    - rh-php70-php-odbc
    - rh-php70-php-opcache
    - rh-php70-php-pdo
    - rh-php70-php-pear.noarch
    - rh-php70-php-pgsql
    - rh-php70-php-process
    - rh-php70-php-pspell
    - rh-php70-php-recode
    - rh-php70-php-snmp
    - rh-php70-php-soap
    - rh-php70-php-tidy
    - rh-php70-php-xml
    - rh-php70-php-xmlrpc
    - rh-php70-php-zip
    - rh-php70-runtime
    - rh-php70-scldevel

- name: Symlink php
  file:
     src: /opt/rh/rh-php70/root/usr/bin/php
     dest: /usr/bin/php
     owner: root
     group: root
     mode: 744
     state: link

- name: Symlink apache
  file:
     src: /opt/rh/httpd24/root/usr/sbin/httpd
     dest: /usr/bin/httpd
     owner: root
     group: root
     mode: 744
     state: link


- name: Download datadog-php rpm
  get_url: url="https://github.com/DataDog/dd-trace-php/releases/download/0.29.0/datadog-php-tracer-0.29.0-1.x86_64.rpm" dest=/opt/datadog-php-tracer.rpm timeout=60 validate_certs=False

- name: Download test_ddtrace.php 
  get_url: url="https://raw.githubusercontent.com/DataDog/dd-trace-php/pawel//test_ddtrace.php/test_ddtrace.php" dest=/opt/rh/httpd24/root/var/www/html/test_ddtrace.php timeout=60 validate_certs=False

- name: Install datadog rpm
  yum:
    name: /opt/datadog-php-tracer.rpm
    state: present
    
- name: Add phpinfo script
  copy:
    src: info.php
    dest: /opt/rh/httpd24/root/var/www/html/info.php
    mode: '0644'
    owner: apache
    group: apache

- name: start apache
  service: 
    name: httpd24-httpd
    state: restarted
